# Use uma imagem base do Node.js
FROM node:18

# Defina o diretório de trabalho dentro do container
WORKDIR /app

# Copie o package.json e o package-lock.json
COPY package*.json ./

# Instale o Angular CLI globalmente
RUN npm install -g @angular/cli

# Limpe o cache do npm e instale as dependências
RUN npm install

# Copie o restante do código para o container
COPY . .

# Exponha a porta usada pelo Angular
EXPOSE 4200

# Comando para iniciar o servidor de desenvolvimento do Angular
CMD ["npm", "start"]